name: Remove label from issues
on:
  issue_comment:
    types: [created]

jobs:
  check_for_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - id: step1
        uses: actions/github-script@v6
        with:
          script: |
            const REMOVE_LABEL = "enhancement"
            console.log("Attempting to remove label ${REMOVE_LABEL}")
            
            const { data } = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log("First response's data:")
            console.log(data)

            
            // Return early if there are no labels
            if (data.length == 0){
              console.log(`Issue has no labels; not attempting to remove label ${REMOVE_LABEL}`)
              return
            }
            
            // Check if REMOVED_LABEL is present
            // Interpret a non-empty filtered array as proof that the label is present
            let filteredData = data.filter(label => label.name == REMOVE_LABEL)
            const labelPresent = filteredData.length > 0
            
            console.log("Label ${REMOVE_LABEL} found! Now deleting it from the issue...")

            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: REMOVE_LABEL
            })
            
