name: Remove labels on issue comment
on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - id: remove-stale
        uses: ./.github/workflows/reusable.yml
        with:
          label-name: "stale"
      - id: remove-waiting-response
        uses: ./.github/workflows/reusable.yml
        with:
          label-name: "waiting-response"
