name: Remove labels on issue comment
on:
  issue_comment:
    types: [created]

jobs:
  remove-foobar:
    uses: ./.github/workflows/reusable.yml
    with:
      label-name: "waiting-response"
  remove-stale:
    uses: ./.github/workflows/reusable.yml
    with:
      label-name: "stale"
