name: Remove "waiting-response" label on issue comment
on:
  issue_comment:
    types: [created]

jobs:
  remove-label:
    uses: ./.github/workflows/reusable.yml
    with:
      label-name: "foobar"
